import type { NextPage } from 'next'
import Head from 'next/head'
import * as S from '../styles/Home.style'

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <footer>footer</footer>
    </S.Container>
  )
}

export default Home
